#pragma once

enum class AppEvent {

    // Window Events
    WINDOW_CREATED,
    WINDOW_DESTROYED,

    WINDOW_POS_CHANGED,
    WINDOW_SIZE_CHANGED,
    WINDOW_TITLE_CHANGED,
    WINDOW_SCREEN_CHANGED,

    WINDOW_MOUSEOVER_CHANGED,
    WINDOW_SELECTION_CHANGED,
    WINDOW_HIDDEN_CHANGED,

    // Screen Events
    SCREEN_DISCOVERY_ADDED,
    SCREEN_DISCOVERY_REMOVED,

    // Mouse input
    MOUSE_MOTION,
    MOUSE_SCROLLED,
    MOUSE_PRESSED,

    MOUSE_ENTER_EXIT_FRAME,
    MOUSE_SELECT_UNSELECT_FRAME,

    // Keyboard input
    KEYS_PRESSED,
    TEXT_ENTERED,

    // Gamepad events
    GAMEPAD_DISCOVERY_ADDED,
    GAMEPAD_DISCOVERY_REMOVED,

    GAMEPAD_INPUT_UPDATE,

    // Module events
    MODULE_DISCOVERY_ADDED,
    MODULE_DISCOVERY_REMOVED,

    MODULE_LOAD_START,
    MODULE_LOAD_SUCCESS,
    MODULE_LOAD_FAILURE,

    MODULE_SHUTDOWN_OK,

    MODULE_SERIALIZATION_SAVE_SUCCESS,
    MODULE_SERIALIZATION_SAVE_FAILURE,
    
    MODULE_SERIALIZATION_LOAD_SUCCESS,
    MODULE_SERIALIZATION_LOAD_FAILURE,

    MODULE_SERIALIZATION_SAVE_FILE_CHANGED,

    MODULE_RUN_STATE_CHANGED, // module paused / resumed
    MODULE_PERMISSIONS_CHANGED,

    // GUI events
    GUI_VISIBILITY_CHANGED,

    // Errors + recovery
    MODULE_RECOVERABLE_ERROR,       // module subprocess (eg. onFrame()) throws a recoverable exception.
    MODULE_UNRECOVERABLE_ERROR,     // module subprocess or startup / shutdown throws an unrecoverable exception - module crashes.
    MODULE_CATASTROPHIC_ERROR,      // module takes down an entire thread and/or the host application.

    SANDBOX_RECOVERABLE_ERROR,      // ditto for core sandbox subprocesses (eg. GUI, ECS, threadmanager, etc).
    SANDBOX_UNRECOVERABLE_ERROR,
    SANDBOX_CATASTROPHIC_ERROR,

    // Application events
    APP_INITIALIZED,                // 
    APP_SHUTDOWN,
};

enum class AppClientCommand {
    CREATE_WINDOW,
    DESTROY_WINDOW,

    WINDOW_SET_POS,
    WINDOW_SET_SIZE,
    WINDOW_SET_TITLE,
    WINDOW_SET_SCREEN,
    WINDOW_SET_MSAA,

    WINDOW_SET_FOCUS,
    WINDOW_SET_HIDDEN,

    CONNECT_WINDOW_ON_GL,
    UNCONNECT_WINDOW_ON_GL,
    PAUSE_WINDOW_ON_GL,

    LOAD_MODULE_PATH,
    RELOAD_MODULE_NAME,

    LOAD_ASSET_PATH,

    MOUSE_SET_POS,
    MOUSE_SET_CURSOR,

    GAMEPAD_SET_BINDING,
    GAMEPAD_SET_CONFIG,

    CREATE_MOUSE_KEYBOARD_DEVICE,
    REMOVE_MOUSE_KEYBOARD_DEVICE,

    CREATE_GAMEPAD_DEVICE,
    REMOVE_GAMEPAD_DEVICE,

    FRAME_SET_FOCUS,

    MODULE_FORCE_LOAD,
    MODULE_FORCE_CLOSE,

    MODULE_SERIALIZATION_DO_LOAD,
    MODULE_SERIALIZATION_DO_SAVE,
    MODULE_SERIALIZATION_SET_SAVE_FILE,

    MODULE_SET_ACTIVE,  // enable / disable onFrame()
    MODULE_SET_VISIBLE, // enable / disable onVisible()

    SANDBOX_SERIALIZATION_DO_LOAD,
    SANDBOX_SERIALIZATION_DO_SAVE,
    SANDBOX_SERIALIZATION_SET_SAVE_FILE,

    MODULE_QUERY_PERMISSIONS,
    MODULE_SET_PERMISSIONS,

    APP_FORCE_RELOAD,
    APP_FORCE_SHUTDOWN,

    APP_SET_WORKER_THREAD_COUNT,
    APP_SET_MODULE_TASK_PRIORITY,
    APP_SET_

    DISPATCH_ASYNC_TASK,



    CANCEL_WINDOW_REMOVAL,
    CANCEL_APP_SHUTDOWN,
};



















